### ISSUE TITLE
Open in browser option

### ISSUE THREAD

**Issue by davestewart** [cytb/simple-autoreload-server#3]
Any chance of something like a `-b` flag to open in the browser?

Right now I have this aliased with `serve="open 'http://localhost:8080'; autoreload-server"` but because of the delay of the node script running, the browser opens to "page not found", then needs a one-time refresh.

Thanks :)

**Comment by cytb** [comment]
I implemented "--execute" and "--stop-on-exit" command-line option.
When this option is passed, server invoke shell-command on ready to accept the client request.
if you need to stop server after command has done,  specify "--execute"  with "--stop-on-exit".

exsamples:
  autoreload-server ./www 8080 --execute "chromium http://localhost:8080"
  autoreload-server ./test 8081 --execute "firefox http://localhost:8081/" --stop-on-exit

Thank you!

**Comment by davestewart** [comment]
Ah, nice!

Can you just call `autoreload-server --execute http://localhost:8080` ?

**Comment by davestewart** [comment]
Or even `-e` ?

**Comment by cytb** [comment]
I ve fixed it now. You can also use '-e'. 
But you need still 'open' command to start default program.
  autoreload-server -e "open http://localhost:8080"

**Comment by davestewart** [comment]
That will certainly make it simpler to run a simple site, thank you :)

I still think a switch to default to launching the browser based on the defaults would be cool. The execute idea is flexible and all, but will people need to launch anything other than the browser?

A one-liner like...

```autoreload-server -b```

... (or -v or -o) would be all that most folks would ever need to type.

Anyway, thank you for the addition!

**Comment by cytb** [comment]
>I still think a switch to launch the default browser based on the current settings would be cool.
hmm.. sorry.   I misunderstood your intention.
Certainly, your idea makes sense when use autoreload-server more easily, and is matched to the use-case.
For some reason I assumed someone uses another or multiple browsers at same time.

and finally '-b' option is available now. sorry to keep you waiting.

**Comment by davestewart** [comment]
Sweet! This is literally the perfect setup for doing online SPA tutorials, thank you so much :D

**Comment by cytb** [comment]
Thank you, too!

**Comment by davestewart** [comment]
Yikes... not sure if I'm doing something I shouldn't, but this doesn't seem to be working after all.

I've tried on Win and Mac, and it runs the server, but doesn't open the browser.

Also, might be an idea to push some release tags, so we can roll back a version if we need to! I'm no expert on NPM, but looks like you can specify the release when you `npm install`

**Comment by cytb** [comment]
>I've tried on Win and Mac, and it runs the server, but doesn't open the browser.

Thank you for always informing useful information. 
I confirmed It doesn't work on WindowsXP/8.1.  It's my fault.
I run tests only on ArchLinux, and the browser-open feature depends on platform specific codes.

Currently, it seems working good on Windows after switched to external npm package ('opener') instead of my own codes. 
It should work fine on Mac. Please update and retry.

>Also, might be an idea to push some release tags, so we can roll back a version if we need to! I'm no expert on NPM, but looks like you can specify the release when you npm install

You can install specific version of package via npm by: 
- version
  npm installl some-package@x.x.x

- tag
  npm installl some-package@tag-name

'npm' installs package with "latest" tag by default.
and I added two tags "alpha" and "latest" to the simple-autoreload-server a while ago.
"alpha" for latest or unstable, and "latest" for somewhat more stable.
(but It still indicates same version now.)

Thank you!

**Comment by davestewart** [comment]
OK, still not quite right on Windows.

```
E:\Learning\2016-01 - CodeCraft Angular\section1>autoreload-server -b
[autoreload #192348 localhost:8080] server started on :8080 at .
```
Followed by an alert: "Windows cannot find http://:::8080. Make sure you typed the name correctly..."

Though it looks in your code that you're building what looks like the right command:

```
 start "" "http://localhost:8080"
```

One thing to think about with the execute function, is that Windows users generally have spaces in path names in the Program Files folder, so `--execute "open %filename"` will likely need escaped quotes round `%filename`. It might be better to have execute call a batch file or script rather than raw code, if that's your intention?

**Comment by cytb** [comment]
oops... These error might be caused by IPv6 address (::).
"--browse" option failed again when setup network to IPv6.
I have fixed it and confirmed that browser is successfully opened on IPv6 Windows8.1.
but it may fail on Mac.

>One thing to think about with the execute function, is that Windows users generally have spaces in path names in the Program Files folder, so --execute "open %filename" will likely need escaped quotes round %filename. It might be better to have execute call a batch file or script rather than raw code, if that's your intention?

Yes,  I think so.
It might cause some problems about string-quotation, variable-expansion,  escaping, relative-path specification, etc.
I suppose it is better to use shell-script for each platforms like you said.

**Comment by davestewart** [comment]
Confirmed working on Windows 10!

Will test on OSX later when I reboot :D

**Comment by cytb** [comment]
I relieved hear that.

>Will test on OSX later when I reboot :smiley:

That would be great, thanks!
