### ISSUE TITLE
-bash: autoreload-server: command not found

### ISSUE THREAD

**Issue by davestewart** [cytb/simple-autoreload-server#5]
Any ideas on this one?

I've had this working before, but have just tried again, installing from scratch, run the command to start the server, and:

```
-bash: autoreload-server: command not found
```

I'm on:
- OSX 10.10
- Node 6.7.0
- NPM 3.10.3

**Comment by cytb** [comment]
Thank you for your reporting.

I don't have a MacOSX envs. and currently, I cant confirm that issue yet.
Please give me a little more time.

**Comment by cytb** [comment]
I'm sorry for my late reply.

I couldn't prepare Mac OSX 10.10 environment.
but I've tried to install package on ArchLinux, Mac OSX 10.11 (node@6.7.0 and npm@3.10.3).
and starting the server by command "autoreload-server" is successfully done on both.

I think that issue was caused by install without  "-g" option, or if you used npm command via nvm, the commands located in "~/.nvm/versions/node/v6.7.0/bin/" might not be exposed.

Could you retry to install package with command "npm i simple-autoreload-server -g", or reinstall nvm?

**Comment by cytb** [comment]
Please reopen the issue if reccured.

**Comment by carloscorreainfo** [comment]
I had same issue, try installing with -g option and work correctly

**Comment by cytb** [comment]
I've fixed install instruction in "README.md".
Thank you for your reporting!
